apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 8080       # external port we’ll talk to on host
    targetPort: 80   # container port nginx listens on
