apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  ports:
  - port: 80           # cluster-internal port
    targetPort: 3000   # container port
    protocol: TCP
  type: ClusterIP
